onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /test/clk
add wave -noupdate /test/rst
add wave -noupdate /test/int
add wave -noupdate /test/wb_addr_o
add wave -noupdate /test/wb_data_i
add wave -noupdate /test/wb_data_o
add wave -noupdate /test/wb_sel_o
add wave -noupdate /test/wb_we_o
add wave -noupdate /test/wb_stb_o
add wave -noupdate /test/wb_cyc_o
add wave -noupdate /test/wb_cti_o
add wave -noupdate /test/wb_bte_o
add wave -noupdate /test/wb_ack_i
add wave -noupdate /test/wb_err_i
add wave -noupdate /test/wb_addr_i
add wave -noupdate /test/wbm_data_i
add wave -noupdate /test/wb_sel_i
add wave -noupdate /test/wb_we_i
add wave -noupdate /test/wb_stb_i
add wave -noupdate /test/wb_cyc_i
add wave -noupdate /test/wb_ack_o
add wave -noupdate /test/wb_rty_o
add wave -noupdate /test/wb_err_o
add wave -noupdate /test/pclk_i
add wave -noupdate /test/pclk
add wave -noupdate /test/hsync
add wave -noupdate /test/vsync
add wave -noupdate /test/ihsync
add wave -noupdate /test/ivsync
add wave -noupdate /test/csync
add wave -noupdate /test/blanc
add wave -noupdate /test/red
add wave -noupdate /test/green
add wave -noupdate /test/blue
add wave -noupdate /test/dvi_de_o
add wave -noupdate /test/dvi_d_o
add wave -noupdate /test/vga_stb_i
add wave -noupdate /test/clut_stb_i
add wave -noupdate /test/scen
add wave -noupdate /test/wd_cnt
add wave -noupdate /test/error_cnt
add wave -noupdate /test/data
add wave -noupdate /test/pattern
add wave -noupdate /test/int_warn
add wave -noupdate /test/n
add wave -noupdate /test/mode
add wave -noupdate /test/thsync
add wave -noupdate /test/thgdel
add wave -noupdate /test/thgate
add wave -noupdate /test/thlen
add wave -noupdate /test/tvsync
add wave -noupdate /test/tvgdel
add wave -noupdate /test/tvgate
add wave -noupdate /test/tvlen
add wave -noupdate /test/hpol
add wave -noupdate /test/vpol
add wave -noupdate /test/cpol
add wave -noupdate /test/bpol
add wave -noupdate /test/p
add wave -noupdate /test/l
add wave -noupdate /test/pn
add wave -noupdate /test/pra
add wave -noupdate /test/paa
add wave -noupdate /test/tmp
add wave -noupdate /test/pd
add wave -noupdate /test/cd
add wave -noupdate /test/pc
add wave -noupdate /test/vbase
add wave -noupdate /test/cbase
add wave -noupdate /test/vbara
add wave -noupdate /test/vbarb
add wave -noupdate /test/bank
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {144386 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {5405070 ps}
